export enum MainEvents {
  PRELOAD_ERROR = 'PRELOAD_ERROR',
  TITLE_BAR_ACTION = 'TITLE_BAR_ACTION',
  HIDE_LAUNCHER = 'HIDE_LAUNCHER',
  DEBUG_WINDOW = 'DEBUG_WINDOW',
  DOWNLOAD_MODPACK = 'DOWNLOAD_MODPACK',
  MINECRAFT_LOADING_PROGRESS = 'MINECRAFT_LOADING_PROGRESS',
  SAVE_SCREENSHOT = 'SAVE_SCREENSHOT',
  LAUNCHER_UPDATE_AVAILABLE = 'LAUNCHER_UPDATE_AVAILABLE',
  LAUNCHER_UPDATE_DOWNLOADED = 'LAUNCHER_UPDATE_DOWNLOADED',
  RESTART_APP = 'RESTART_APP',
}
