export enum MainInvokeEvents {
  GET_MINECRAFT_PATH = 'GET_MINECRAFT_PATH',
  GET_MODPACKS_SCREENSHOTS = 'GET_MODPACKS_SCREENSHOTS',
  DELETE_SCREENSHOT = 'DELETE_SCREENSHOT',
  CHECK_MODPACK_UPDATES = 'CHECK_MODPACK_UPDATES',
  CHECK_JAVA = 'CHECK_JAVA',
  DELETE_MODPACK = 'DELETE_MODPACK',
  GET_LAUNCHER_LOGS = 'GET_LAUNCHER_LOGS',
}
